Release/rtc ng/4.2.0 unreal quickstart
AgoraIO/agora_doc_source pull request #3274
Opened 2023-07-20 14:41 UTC by jinyuagora

2023-07-25 07:52 UTC, Cilla-luodan commented on markdown/RTC 4.x/unreal/get-started/start_call_audio_bp_ng.md
> +    1. 选择 **Blueprint** 或 **C++**。
一般多级列表这里，儿子们会用 a b c d，要不会显得很奇怪。

2023-07-25 07:53 UTC, Cilla-luodan commented on markdown/RTC 4.x/unreal/get-started/start_call_audio_bp_ng.md
> +    1. 选择 **Blueprint** 或 **C++**。
预览页面里，1 这里看起来有点奇怪，可以 check 一下
![Uploading image.png…]()

2023-07-25 07:55 UTC, Cilla-luodan commented on markdown/RTC 4.x/unreal/get-started/start_call_audio_bp_ng.md
> +    2. 根据你开发的目标平台选择 **Desktop / Console** 或 **Mobile / Tablet**。
2 3 和 4 的格式在预览中都有点问题，加粗和图没显示出来，应该要换行

2023-07-25 08:33 UTC, Cilla-luodan commented on markdown/RTC 4.x/unreal/get-started/start_call_audio_bp_ng.md
> +上述步骤中已经创建了 **onJoinChannelSuccess**、**onLeaveChannel**、**onUserJoined** 和 **onUserOffline** 回调函数，该步骤中会具体实现这些回调。
“该步骤中会具体实现这些回调。”看起来有点怪，这句话是否以改为：
将之前创建的 xxx 回调函数按照以下实现步骤进行配置。

2023-07-25 08:40 UTC, Cilla-luodan commented on markdown/RTC 4.x/unreal/get-started/start_call_bp_ng.md
> +        | `onJoinChannelSuccess` | 成功加入频道回调。 |  <ul><li>`channel`: (String) 频道名。</li><li>`uid`: (Integer64) 加入频道的本地主播的用户 ID。</li><li>`elapsed`: (Integer) 从本地调用 `joinChannel` 开始到发生此事件过去的时间（毫秒）。</li></
对于 video call 来说，是否把“本地主播”都改成“本地用户”；“远端主播”都改成 "远端用户"，这样更好理解一些。

2023-07-26 03:51 UTC, WinterPu commented on markdown/RTC 4.x/unreal/get-started/start_call_audio_bp_ng.md
> +- 两台设备，不可使用虚拟机。操作系统与编译器要求如下：
设备需求感觉可以不用写了

因为存在过时或者错误 （比如 UE5 Android 要求是 8 ）

 感觉可以直接refer UE 的一些链接
 
 以下附上的都是UE5的文档，文档内可以切换版本到4.27
   
 UE5 Android Compabitliy https://docs.unrealengine.com/5.0/en-US/android-support-for-unreal-engine/ 
    
IOS Requirement ： https://docs.unrealengine.com/5.0/en-US/ios-ipados-and-tvos-support-for-unreal-engine/
    
 Hardware And Software Require https://docs.unrealengine.com/5.0/en-US/hardware-and-software-specifications-for-unreal-engine/
    

但请保留以下这条：

- 32 位 Windows 仅支持 Unreal Engine 4 及以下版本，你需要在 `AgoraPluginLibrary.Build.cs` 文件中将 Windows 32 相关的代码取消注释。

2023-07-26 03:51 UTC, WinterPu commented on markdown/RTC 4.x/unreal/get-started/start_call_audio_bp_ng.md
> +参考以下步骤或 [Unreal 官方操作指南](https://docs.unrealengine.com/5.1/en-US/onboarding-guide-for-unreal-engine-games-licensees/)创建一个 **Unreal** 项目。如果已有 **Unreal** 项目，可进行下一步[集成 SDK](#集成-sdk)。
链接换一换 https://docs.unrealengine.com/4.27/en-US/Basics/Projects/Browser/

2023-07-26 03:51 UTC, WinterPu commented on markdown/RTC 4.x/unreal/get-started/start_call_audio_bp_ng.md
> +    2. 根据你开发的目标平台选择 **Desktop / Console** 或 **Mobile / Tablet**。
这个可以不用写，这个关系不大。

2023-07-26 03:51 UTC, WinterPu commented on markdown/RTC 4.x/unreal/get-started/start_call_bp_ng.md
> +   | 4    | **Set Basic Video Call Widget**   | 自定义   | 设置用户界面。步骤如下：<ol><li>创建 **BasicVideoCallWidget** 变量。</li><li>选择变量的 **Variable Type** 为 **BP_Video Widget**，即已经创建好的用户界面，用于在蓝图中存储对用户界面的引用。</li><li
提一下，这个节点就是拖曳刚刚创建的变量后会出现get 还是 set ，选择 set 生成的。

2023-07-26 03:51 UTC, WinterPu commented on markdown/RTC 4.x/unreal/get-started/start_call_bp_ng.md
> +   | 7    | **Check Permission**   | 自定义   | (可选) 检查是否已获取视频通话所需的系统权限，如访问摄像头和麦克风等。<div class="alert note">该节点仅适用于 Android。</div> |
不是仅适用于Android， 是目前这个只检查了Android 权限，其他的都靠别的手段检查

2023-07-26 09:28 UTC, WinterPu commented on markdown/RTC 4.x/migration-guide/zh-CN/migration_guide_unreal_ng.md
> +在项目文件夹中增加 `#include "AgoraPluginInterface.h"`，以直接导入 v4.x SDK 中的所有基础类。
改为：在项目文件中引用头文件：`#include "AgoraPluginInterface.h"`， 以直接导入 v4.x SDK 中的主要基础类。
有需要可以在 AgoraPlugin\Private\AgoraCppPlugin\include\AgoraHeaderBase.h 中补充，或者直接include 所需文件

2023-07-26 09:28 UTC, WinterPu commented on markdown/RTC 4.x/migration-guide/zh-CN/migration_guide_unreal_ng.md
> +- SDK 优化了视频渲染的逻辑，无需再调用 `OnTick` 函数。你需要手动删除项目文件中跟 `OnTick` 相关的代码。
个人觉得这里不算优化渲染逻辑（并没有做性能上的优化）
建议是改成：简化了视频渲染的实现步骤，无需主动调用 AgoraRtcEngine（3.X 的叫法） 的 OnTick函数，转而交由 VideoRenderManager 去处理

2023-07-26 09:28 UTC, WinterPu commented on markdown/RTC 4.x/migration-guide/zh-CN/migration_guide_unreal_ng.md
> +### 2.（可选）导入基础类
这里我是觉得 导入基础类三号标题，看上去比下面重要的改动重要。

2023-07-27 03:43 UTC, jinyuagora commented on markdown/RTC 4.x/unreal/get-started/start_call_bp_ng.md
> +   | 4    | **Set Basic Video Call Widget**   | 自定义   | 设置用户界面。步骤如下：<ol><li>创建 **BasicVideoCallWidget** 变量。</li><li>选择变量的 **Variable Type** 为 **BP_Video Widget**，即已经创建好的用户界面，用于在蓝图中存储对用户界面的引用。</li><li
细!

2023-07-27 09:10 UTC, jinyuagora commented on markdown/RTC 4.x/release-notes/en-US/framework/release_unreal_ng.md
> +**1. Video capture**
两个问题：
1. Unreal 算全平台支持的框架，发版说明应该是要体现对应的平台，比如视频采集这里应该要加 (Windows, iOS)
2. audio 的发版说明是不是也需要

2023-08-02 16:39 UTC, billy-the-fish requested changes

2023-08-02 16:39 UTC, billy-the-fish commented on markdown/RTC 4.x/migration-guide/en-US/migration_guide_unreal_ng.md
> +See [Project setup]() for more information about integrating the v4.0.0 SDK into your project.
To integrate Video SDK for Unreal Engine v4.x into your project, see ..

2023-08-02 16:39 UTC, billy-the-fish commented on markdown/RTC 4.x/migration-guide/en-US/migration_guide_unreal_ng.md
> +This section introduces the main changes between v3.x and v4.2.1. In order to retain Agora functionality in your app, update the code in your app according to your scenarios.
This section explains the main changes between Video SDK for Unreal Engine v3.x and v4.x. Use this information to upgrade your app.

2023-08-02 16:39 UTC, billy-the-fish commented on markdown/RTC 4.x/migration-guide/en-US/migration_guide_unreal_ng.md
> +The Unreal C++ SDK is built on top of the Native C++ SDK, it includes all the changes from Native SDK v3.x to v4.x. For specific details about these changes, see [Migrate from Video SDK 3.x]().
Video SDK for Unreal Engine v4.x is based on Video SDK for C++ v4.x. First follow the steps in [Migrate from Video SDK 3.x](https://docs.agora.io/en/video-calling/develop/migration-guide?platform=windows).

2023-08-02 16:39 UTC, billy-the-fish commented on markdown/RTC 4.x/migration-guide/en-US/migration_guide_unreal_ng.md
> +- The v4.x SDK simplifies the implementation steps for video rendering, eliminating the need to actively call the `OnTick` function in `AgoraRtcEngine`. Instead, it is automatically handled by the `V
for video rendering. The `OnTick` function is handled by the `VideoRenderingManager`. Remove all code related to ...

2023-08-02 16:39 UTC, billy-the-fish commented on markdown/RTC 4.x/migration-guide/en-US/migration_guide_unreal_ng.md
> +- Modify the project folder and add a reference to the header file `#include "AgoraPluginInterface.h"` to directly import all the basic classes from the v4.x SDK. Depending on your specific needs, yo
To directly import Video SDK for Unreal Engine v4.x objects, include `AgoraPluginInterface.h` into all your classes. You  may also need `AgoraPlugin\Private\AgoraCppPlugin\include\AgoraHeaderBase.h`.

2023-08-02 16:39 UTC, billy-the-fish commented on markdown/RTC 4.x/release-notes/en-US/framework/release_bluerprint_ng.md
> +This release is the first version of RTC Unreal Blueprint SDK.
This is the first release of Video SDK for Unreal Blueprint.

2023-08-02 16:39 UTC, billy-the-fish commented on markdown/RTC 4.x/release-notes/en-US/framework/release_bluerprint_ng.md
> +This SDK, designed by Agora for developers using Unreal Blueprint, aims to provide a simple and user-friendly real-time interactive solution for Unreal Engine users.
Video SDK for Unreal Blueprint provides a ...

2023-08-02 16:39 UTC, billy-the-fish commented on markdown/RTC 4.x/release-notes/en-US/framework/release_bluerprint_ng.md
> +The SDK offers a visual interface and a set of intuitive and easy-to-use nodes, allowing developers to effortlessly implement real-time interactive features in games or apps within the Unreal project
Video SDK for Unreal Blueprint offers a ... notes. This enables developer to ... . You don't need to know C++, just drag, connect and configure nodes.

2023-08-02 16:39 UTC, billy-the-fish commented on markdown/RTC 4.x/release-notes/en-US/framework/release_bluerprint_ng.md
> +Agora provides an open source [example project](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/tree/main/Agora-Unreal-SDK-Blueprint-Example) on GitHub for your reference.
the open source

2023-08-02 16:39 UTC, billy-the-fish commented on markdown/RTC 4.x/release-notes/en-US/framework/release_bluerprint_ng.md
> +Refer to the following documentations to integrate the SDK into your project, and add real-time engagement functionalities to the app.
To integrate real-time engagement functionality into your app using Video SDK for Unreal Engine, see:


I don't see why you are linking to the SDK docs rather than blueprint.

2023-08-02 16:39 UTC, billy-the-fish commented on markdown/RTC 4.x/release-notes/en-US/framework/release_unreal_audio_ng.md
> +If you use the features mentioned in this section, ensure that you modify the implementation of the relevant features after upgrading the SDK.
The following compatibility changes are made in this release. Update your app to handle these changes.

2023-08-02 16:39 UTC, billy-the-fish commented on markdown/RTC 4.x/release-notes/en-US/framework/release_unreal_audio_ng.md
> +As of this release, you can use the following methods to open files with a URI starting with `content://` : `startAudioMixing`, `playEffect`, and `openWithMediaSource`.
You can now use the following methods ...

2023-08-02 16:39 UTC, billy-the-fish commented on markdown/RTC 4.x/release-notes/en-US/framework/release_unreal_audio_ng.md
> +- Occasional crashes occur on Android devices when users joining or leaving a channel. (Android)
join or leave a

2023-08-02 16:39 UTC, billy-the-fish commented on markdown/RTC 4.x/release-notes/en-US/framework/release_unreal_audio_ng.md
> +- When the host frequently switching the user role between broadcaster and audience in a short period of time, the audience members cannot hear the audio of the host.
switches

2023-08-02 16:39 UTC, billy-the-fish commented on markdown/RTC 4.x/release-notes/en-US/framework/release_unreal_audio_ng.md
> +- When the playback of the local music finished, the `onAudioMixingFinished` callback was not properly triggered. (Android)
When local music playback finished, the ..

2023-08-02 16:39 UTC, billy-the-fish commented on markdown/RTC 4.x/release-notes/en-US/framework/release_unreal_audio_ng.md
> +- At the moment when a user left a channel, a request for leaving was not sent to the server and the leaving behavior was incorrectly determined by the server as timed out.
a leave request was not sent to the server. Leaving was incorrectly determined by the server as a timeout.

2023-08-02 16:39 UTC, billy-the-fish commented on markdown/RTC 4.x/release-notes/en-US/framework/release_unreal_audio_ng.md
> +- Inability to join channels caused by SDK's incompatibility with some older versions of AccessToken.
You could not join channels because Video SDK for Unreal Engine did not accept older authentication tokens.

2023-08-03 02:12 UTC, Cilla-luodan commented on markdown/RTC 4.x/migration-guide/en-US/migration_guide_unreal_ng.md
> +**Basic changes**
This is to explain two kinds of changes of the Unreal SDK：
part A: same as the Native SDK;
part B: the Unreal only changes

Anyway, you can edit is as you like on EN site

2023-08-03 02:18 UTC, Cilla-luodan commented on markdown/RTC 4.x/migration-guide/en-US/migration_guide_unreal_ng.md
> +- The `agora::rtc::ue4::AgoraRtcEngine*` interface class is changed to `agora::rtc::ue::RtcEngineProxy*`, you need to update the code in the  project files.
In the current API ref, we use "interface class" to describe the top level class.

2023-08-03 02:50 UTC, Cilla-luodan commented on markdown/RTC 4.x/release-notes/en-US/framework/release_bluerprint_ng.md
> +Refer to the following documentations to integrate the SDK into your project, and add real-time engagement functionalities to the app.
This is an introduction to the quick start guides and API ref of blueprint for the users. 
It's a common template for the first release of a platform.
Just update the urls to the EN guides.

2023-08-03 03:00 UTC, Cilla-luodan commented on markdown/RTC 4.x/release-notes/en-US/framework/release_unreal_audio_ng.md
> +If you use the features mentioned in this section, ensure that you modify the implementation of the relevant features after upgrading the SDK.
Actually the release notes of Unreal C++ are not within the scope of this review, as they are inherited from the reviewed and published Native release notes. Nonetheless, thank you for your comments.

2023-10-11 04:09 UTC, merged