New YiCAT updates
AgoraIO/agora_doc_source pull request #3578
Opened 2024-04-11 06:33 UTC by Cilla-luodan

2024-04-12 10:04 UTC, Cilla-luodan commented on en-US/dita/RTC-NG/API/api_irtcengineex_getcallidex.dita
> +    <title>getCallIdEx</title>
啊啊啊啊啊啊

2024-04-12 10:06 UTC, Cilla-luodan commented on en-US/dita/RTC-NG/API/api_irtcengine_pushaudioframe2.dita
> +                <li>Call <xref keyref="createCustomAudioTrack"/> to create a custom audio track and obtain the audio track ID.</li>
obtain -> get ?

2024-04-12 10:14 UTC, Nero-Hu commented on en-US/dita/RTC-NG/API/api_irtcengine_iscameracenterstagesupported.dita
> +            <p>No.</p>
restrictions 感觉应该是 none？

2024-04-12 10:15 UTC, Cilla-luodan commented on en-US/dita/RTC-NG/API/api_irtcengine_setaudioeffectpreset.dita
> +                    <li><ph keyref="ROOM_ACOUSTICS_CHORUS" />: A chorus audio effect. Agora recommends using this effect in chorus scenarios to enhance the sense of depth and dimension in the vocals.
vocals.y？ 是个人签名么

2024-04-12 10:33 UTC, Suri539 commented on en-US/dita/RTC-NG/API/callback_ifaceinfoobserver_onfaceinfo.dita
> +                    <li>faces: Object sequence. Includes recognized facial information, with each face corresponding to an object.</li>
Includes 前面没主语，要么前面不用 .

2024-04-12 10:33 UTC, Suri539 commented on en-US/dita/RTC-NG/API/callback_ifaceinfoobserver_onfaceinfo.dita
> +                        <li>pitch: Head pitch angle.. A positve value meansing looking down, while a negative value means looking up.</li>
- 多余符号
- meansing -> means
- 下面几个参数有同样的问题

2024-04-12 10:33 UTC, Suri539 commented on en-US/dita/RTC-NG/API/callback_ifaceinfoobserver_onfaceinfo.dita
> +            <li><codeph><ph keyref="true"/></codeph>: Facial information JSON parsing successful.</li>
succeeds. 
下面 fails.

2024-04-12 10:33 UTC, Suri539 commented on en-US/dita/RTC-NG/API/callback_irtcengineeventhandler_onlocalvideostatechanged.dita
> +            <li props="cpp apple framework">The app goes to the background and the system reclaims the camera.</li>
revoke camera permissions reclaim 不太适用这个语境，是指夺回xxx（而且是有造成损失的

2024-04-12 10:33 UTC, Suri539 commented on en-US/dita/RTC-NG/API/class_cameracapturerconfiguration.dita
> +          <li props="android cpp unreal bp flutter unity rn">To set the focal length type of the camera, it is only supported to specify the camera through <parmname>cameraDirection</parmname>, and n
and not suppored to specify it through <parmname>cameraId</parmname>后面那一部分可以不要

2024-04-12 10:33 UTC, Suri539 commented on en-US/dita/RTC-NG/API/class_cameracapturerconfiguration.dita
> +        <pd>The camera ID. <ph props="cpp unreal bp electron flutter">The maximum length is <xref keyref="MAX_DEVICE_ID_LENGTH_TYPE"/>.</ph><note type="attention" props="cpp unreal bp unity flutter">
This parameter

2024-04-15 02:22 UTC, Cilla-luodan commented on en-US/dita/RTC-NG/API/api_irtcengine_switchcamera2.dita
> +                <pd>The camera ID. You can obtain the camera ID through the Android native system API, see <xref keyref="camera1-link"/> and <xref keyref="camera2-link"/> for details.</pd>
一般获取 ID 啥的都用 get 吧~

2024-04-15 02:25 UTC, Cilla-luodan commented on en-US/dita/RTC-NG/API/api_imediaengine_registerfaceinfoobserver.dita
> +            <p>You can call this method to register the <xref keyref="onFaceInfo"/> callback to receive the facial information processed by Agora speech driven extension. When calling this method to
will trigger -> triggers
registered -> have registered

2024-04-15 02:59 UTC, jinyuagora commented on en-US/dita/RTC-NG/API/enum_audioeffectpreset.dita
> +    <shortdesc id="short"><ph id="shortdesc">Preset voice effects.</ph></shortdesc>
这里为什么改成 voice effect 了，看下文还是用的 audio effect，统一一个用法？

2024-04-15 03:00 UTC, jinyuagora commented on en-US/dita/RTC-NG/API/enum_audioeffectpreset.dita
> +                <pd>The audio effect of chorus. Agora recommends using this effect in chorus scenarios to enhance the sense of depth and dimension in the vocals.y</pd>
句尾多了一个 y

2024-04-15 03:18 UTC, jinyuagora commented on en-US/dita/RTC-NG/API/enum_audioeffectpreset.dita
> +                    <p>A 3D voice effect that makes the voice appear to be moving around the user. The default movement cycle is 10 seconds. After setting this effect, you can call <xref keyref="setA
movement cycle 感觉不是特别适合用于声音的环绕，这里是为啥要改来的

2024-04-15 03:19 UTC, jinyuagora commented on en-US/dita/RTC-NG/API/enum_audioeffectpreset.dita
> +                    <p>A senior man's voice.</p>
直接懂了 年轻男人 junior man

2024-04-15 03:23 UTC, jinyuagora commented on en-US/dita/RTC-NG/API/enum_camerastabilizationmode.dita
> +    <shortdesc id="short"><ph id="shortdesc">Camera stabilization mode.</ph></shortdesc>
mode -> modes

2024-04-15 03:24 UTC, Suri539 commented on en-US/dita/RTC-NG/API/class_simulcaststreamconfig.dita
> +                <pd><ph>The video dimension. </ph><ph props="android cpp unreal bp unity electron rn flutter cs">See <xref keyref="VideoDimensions" />. </ph><ph>The default value is 50% of the high-q
这个描述感觉有点不太清晰，建议把 high-quality video stream 具体的分辨率写一下

2024-04-15 03:24 UTC, Suri539 commented on en-US/dita/RTC-NG/API/class_videocanvas.dita
> +                    <pd props="native flutter unity cs electron rn">The video display window. <ph props="android">It must be one <xref keyref="SurfaceView-link"/> or <xref keyref="TextureView-link"/>
canvas 后面有多余空格。if both xxx 应该另起一句

2024-04-15 03:24 UTC, Suri539 commented on en-US/dita/RTC-NG/API/class_videocanvas.dita
> +                    <pd>A container that provides video images. When you use this member, you need to implement texture drawing in OPENGL yourself. See <xref keyref="SurfaceTexture-link"/>.<note type
comment 同上

2024-04-15 03:24 UTC, Suri539 commented on en-US/dita/RTC-NG/API/class_videocanvas.dita
> +                        <li><codeph><ph keyref="false"/></codeph>: (default) The receiver disables alpha mask rendering.</li>
Default

2024-04-15 03:25 UTC, jinyuagora commented on en-US/dita/RTC-NG/API/enum_camerastabilizationmode.dita
> +                    <pd>0: Automatic camera stabilization, the system automatically selects a stabilization mode based on the status of the camera. However, the latency is relatively high in this mod
逗号连接两个独立的句子不太对
, 改为 ;
或者
the system 前面加个连接词 where the system

2024-04-15 03:29 UTC, jinyuagora commented on en-US/dita/RTC-NG/API/enum_localaudiostreamreason.dita
> +                    <pd props="cpp unreal bp ios unity rn flutter">8:<ph props="cpp unreal bp unity flutter"> (Android and iOS only) </ph>The local audio capture is interrupted by a system call, smar
空格要调回之前的，否则 ios 和 rn 发布出来 8: 和 The 中间没空格

2024-04-15 03:30 UTC, Suri539 commented on en-US/dita/RTC-NG/API/api_irtcengine_setcamerastabilizationmode.dita
> +            <p>When shooting on the move, in low light conditions, or handheld, you can set the camera stabilization mode to reduce the impact of camera shake and get a more stable, clear picture.</p
or handheld -> or with mobile devices, 手持就是指用移动设备来拍吧 handheld 原文这样写有语法问题，所以改了下

2024-04-15 03:32 UTC, jinyuagora commented on en-US/dita/RTC-NG/API/enum_localvideostreamreason.dita
> +                <pd>14: <ph props="cpp">(Android only) </ph>Video capture is interrupted.. Possible reasons include the following:<ul>
..

2024-04-15 03:39 UTC, Cilla-luodan commented on en-US/dita/RTC-NG/API/enum_camerafocallengthtype.dita
> +                    <pd>3: Telephoto lens.<note type="attention" props="cpp unreal bp flutter unity rn">This enumerator applies to iOS only.</note>
一般这种直接加 ph 打上 props 写 For A and B only 就行

2024-04-15 03:42 UTC, Cilla-luodan commented on en-US/dita/RTC-NG/API/enum_camerastabilizationmode.dita
> +                    <pd>0: Automatic camera stabilization, the system automatically selects a stabilization mode based on the status of the camera. However, the latency is relatively high in this mod
那我改成句号也行？

2024-04-15 06:56 UTC, Cilla-luodan commented on en-US/dita/RTC-NG/API/class_simulcaststreamconfig.dita
> +                <pd><ph>The video dimension. </ph><ph props="android cpp unreal bp unity electron rn flutter cs">See <xref keyref="VideoDimensions" />. </ph><ph>The default value is 50% of the high-q
木有具体分辨率，原始大流的分辨率不管是多少，小流的默认分辨率都是它的一半

2024-04-15 07:26 UTC, Suri539 commented on en-US/dita/RTC-NG/API/enum_audioeffectpreset.dita
> +                    <p>A 3D voice effect that makes the voice appear to be moving around the user. The default movement cycle is 10 seconds. After setting this effect, you can call <xref keyref="setA
记忆库自己改的..

2024-04-15 12:52 UTC, atovpeko requested changes

2024-04-15 12:52 UTC, atovpeko commented on en-US/dita/RTC-NG/API/api_irtcengine_setcamerastabilizationmode.dita
> +                <li>After enabling camera stabilization, the higher the camera stabilization level, the smaller the camera's field of view and the greater the camera's latency. To ensure user experie
```suggestion
                <li>After enabling camera stabilization, the higher the camera stabilization level, the smaller the camera's field of view and the greater the camera's latency. To improve user experience, it is recommended that you set the <parmname>mode</parmname> parameter to <apiname keyref="CAMERA_STABILIZATION_MODE_LEVEL_1"/>.</li>
```

2024-04-15 12:52 UTC, atovpeko commented on en-US/dita/RTC-NG/API/class_videocanvas.dita
> +                    <pd>A container that provides video images. When you use this member, you need to implement texture drawing in OPENGL yourself. See <xref keyref="SurfaceTexture-link"/>.<note type
```suggestion
                    <pd>A container that provides video images. When you use this member, you need to implement texture drawing in OPENGL yourself. See <xref keyref="SurfaceTexture-link"/>.<note type="attention">In one <apiname keyref="VideoCanvas"/>, you can only choose to set either <parmname>view</parmname> or <parmname>surfaceTexture</parmname>. If both are set, only the settings in <parmname>view</parmname> take effect.</note></pd>
```

2024-04-15 12:52 UTC, atovpeko commented on en-US/dita/RTC-NG/API/enum_localaudiostreamreason.dita
> +                    <pd>7: <ph props="cpp unreal bp unity flutter">(Windows and macOS only) </ph>No local audio capture device. Remind your users to check whether the speaker is connected to the devi
control panel maybe?

2024-04-15 12:52 UTC, atovpeko commented on en-US/dita/RTC-NG/API/enum_localvideostreamreason.dita
> +                <pd props="cpp unreal bp mac flutter unity electron"><ph>11:</ph><ph props="cpp unreal bp flutter unity electron"> (macOS and Windows only)</ph><ph> The shared windows is minimized wh
```suggestion
                <pd props="cpp unreal bp mac flutter unity electron"><ph>11:</ph><ph props="cpp unreal bp flutter unity electron"> (macOS and Windows only)</ph><ph> The shared window is minimized when you call the <xref keyref="startScreenCaptureByWindowId"/> method to share a window. The SDK cannot share a minimized window. Please prompt the user to unminimize the shared window.</ph></pd>
```

2024-04-15 12:52 UTC, atovpeko commented on en-US/dita/RTC-NG/API/enum_localvideostreamreason.dita
> +                    <li>The camera is being occupied by another app. Prompt the user to check if the camera is being occupied by another app.</li>
```suggestion
                    <li>The camera is being occupied by another app. Prompt the user to check if the camera is being used by another app.</li>
```

2024-04-16 06:18 UTC, merged